# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-PSSC7HqfhGrgVMY8dJPqV9v9iwDqs42
"""

import pandas as pd
import numpy as np

csv1 = pd.read_csv("/content/Audible_Catlog.csv")
csv1

csv2 = pd.read_csv("/content/Audible_Catlog_Advanced_Features.csv")
csv2

df = csv1.merge(csv2, how="inner", on="Book Name")
df

df = df.drop(['Author_y','Rating_y', 'Price_x'], axis=1)
df

df['Number of Reviews'] = df[['Number of Reviews_x', 'Number of Reviews_y']].max(axis=1)
df

df = df.drop_duplicates()
df

df = df.drop(['Number of Reviews_x', 'Number of Reviews_y'], axis=1)
df

df.info()

df.isnull().sum()

df = df.dropna(subset=['Description'])
df

df['Number of Reviews'] = df['Number of Reviews'].fillna(0).astype(int)
df.info()

df

df = df.copy()
df['Ranks and Genre'] = df['Ranks and Genre'].str.lstrip(',')
df

#df['Rating_x'].value_counts()
#df.info()
#df.isnull().sum()
df = df.copy()
df['Rating_x'] = df['Rating_x'].replace(-1.0, np.nan)
df['Listening Time'] = df['Listening Time'].replace("-1", "None")
df['Ranks and Genre'] = df['Ranks and Genre'].replace("-1", "None")
df

df = df.dropna(subset=['Rating_x'])
df

df.columns = ['Book Name', 'Author Name', 'Rating', 'Price', 'Description', 'Listening Time', 'Ranks and Genre', 'Number of Reviews']
df